### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by Luckyaremu**

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Luckyaremu    
#### Great Job so far, but there are a few more things required. 
#### General
- [ ] Concerning the comments in your code: It’s better to delete commented code. If you need to review a previous version of your code, use git history
- [ ] Files not related to the project should not be committed e.g  package-lock.json
### Make changes and submit another code review request.
*Happy coding*

**Review by Forison — COMMENTED** [review]
### Pull request under review by Addo

**Review by Forison — APPROVED** [review]
## Status::Approved💚 
# Hi @Luckyaremu🙌,
Good job😇 on implementing the changes raised in the previous review.
#### Go ahead and merge to master
### [optional] 
* [ ] Pull Request has a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
### See you in the next project
#### Happy coding💻
#### Addo Forison

**Pull request merged**
